name: my_tflite_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  tflite_v2: ^1.0.0
  firebase_core: ^2.10.0
  cloud_firestore: ^4.9.0
  fl_chart: ^0.65.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/120+ Cute Summer Phone Aesthetic Wallpapers (Free, High-Res).jfif
    - assets/download.jfif
    - assets/Midjourney_  Vibrant rural landscape with sustainable farming and renewable energy_.jfif